name: four_secrets_wedding_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.11.0
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.3
  build_runner: ^2.4.15
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  expandable_text: ^2.3.0
  ffi: ^2.1.3
  flick_video_player: ^0.9.0
  flutter_animated_icons: ^1.0.1
  flutter_flip_card: ^0.0.6
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  flutter_sticky_header: ^0.7.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.2.1
  sticky_footer_scrollview: ^1.1.1
  url_launcher: ^6.3.1
  video_player: ^2.9.5
  
  # State Management & Data Persistence
  provider: ^6.1.1
  
  # Image Handling
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0
  
  # Permissions
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  flutter_switch: ^0.3.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.6
  firebase_app_check: ^0.3.2+5
  # UI Components
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4
  
  # Utils
  path: ^1.8.3
  uuid: ^4.2.2
  intl: ^0.20.2
  staggered_grid_view: ^0.0.1
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  see_more: ^0.0.5
  android_alarm_manager_plus: ^4.0.7




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/secrets-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  # Pictures
  assets:
    - assets/images/logo/
    - assets/images/home/
    - assets/images/inspirations/
    - assets/images/logo/
    - assets/images/about_me/
    - assets/icons/
    - assets/images/bachelorette_party/
    - assets/images/hair_makeup/
    - assets/images/budget/
    - assets/icons/oval.png
    - assets/icons/circle.png
    - assets/icons/square.png
    - assets/icons/rectangle.png
    - assets/images/background/home_bg.png
    - assets/images/showroom_event/
    - assets/images/card/
    - assets/images/gaestelist/
    - assets/images/kontakt/
    - assets/images/background/
    - assets/images/checklist/
    - assets/images/divider/
    

  # Videos
#    - assets/videos/hair_makeup.mp4
    - assets/videos/bachelorette.mp4
    - assets/videos/akupunktur.mp4
#    - assets/videos/about_me.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: 
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
