name: four_secrets_wedding_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: "none"

version: 1.0.2+2

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.11.0
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.3
  build_runner: ^2.4.15
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  expandable_text: ^2.3.0
  ffi: ^2.1.3
  flick_video_player: ^0.9.0
  flutter_animated_icons: ^1.0.1
  flutter_flip_card: ^0.0.6
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  flutter_sticky_header: ^0.7.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.2.1
  sticky_footer_scrollview: ^1.1.1
  url_launcher: ^6.3.1
  video_player: ^2.9.5
  flutter_dotenv: ^5.1.0

  # State Management & Data Persistence
  provider: ^6.1.1

  # Image Handling
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0

  # Permissions
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  flutter_switch: ^0.3.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_app_check: ^0.3.2+5
  # UI Components
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4

  # Utils
  path: ^1.8.3
  uuid: ^4.2.2
  intl: ^0.19.0
  chat_gpt_sdk: ^3.1.5
  dash_chat_2: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/secrets-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  # Pictures
  assets:
    - assets/images/logo/secrets-logo.jpg
    - assets/images/inspirations/Bacheloretteparty.jpg
    - assets/images/inspirations/Band_DJ.jpg
    - assets/images/inspirations/Braut_Braeutigam_Atelier.jpg
    - assets/images/inspirations/Cake.jpg
    - assets/images/inspirations/Florist_Floristin.jpg
    - assets/images/inspirations/Fotograf_Fotografin.jpg
    - assets/images/inspirations/Kosmetische_Akupunktur.jpg
    - assets/images/inspirations/Hair_und_MakeUp_Styling.jpg
    - assets/images/inspirations/Location.jpg
    - assets/images/inspirations/Catering.jpg
    - assets/images/inspirations/Patiserie.jpg
    - assets/images/inspirations/Unterhaltung.jpg
    - assets/images/inspirations/Tanzschule.jpg
    - assets/images/inspirations/Gesang.jpg
    - assets/images/inspirations/Personal_Training.jpg
    - assets/images/inspirations/Wedding_Designer.jpg
    - assets/images/inspirations/Papeterie.jpg
    - assets/images/inspirations/Trauredner.jpg
    - assets/images/inspirations/Trauringe.jpg
    - assets/images/logo/secrets-logo-app-bar.jpg
    - assets/images/about_me/about_me_header.jpg
    - assets/images/about_me/about_me_main.jpg
    - assets/icons/secrets-icon.png
    - assets/images/bachelorette_party/bachelorette_party_1.png
    - assets/images/bachelorette_party/bachelorette_party_2.jpg
    - assets/images/bachelorette_party/bachelorette_party_3.jpg
    - assets/images/bachelorette_party/bachelorette_party_4.jpg
    - assets/images/bachelorette_party/bachelorette_party_5.jpg
    - assets/images/bachelorette_party/bachelorette_party_6.jpg
    - assets/images/bachelorette_party/bachelorette_party_7.jpg
    - assets/images/bachelorette_party/bachelorette_party_8.jpg
    - assets/images/bachelorette_party/bachelorette_party_9.jpg
    - assets/images/hair_makeup/hair_makeup_1.png
    - assets/images/hair_makeup/hair_makeup_2.jpg
    - assets/images/hair_makeup/hair_makeup_3.jpg
    - assets/icons/oval.png
    - assets/icons/circle.png
    - assets/icons/square.png
    - assets/icons/rectangle.png
    - assets/images/hair_makeup/hair_makeup_1.png
    - assets/images/hair_makeup/hair_makeup_2.jpg
    - assets/images/hair_makeup/hair_makeup_3.jpg
    - assets/images/hair_makeup/hair_makeup_4.jpg
    - assets/images/hair_makeup/hair_makeup_5.jpg
    - assets/images/hair_makeup/hair_makeup_6.jpg
    - assets/images/hair_makeup/hair_makeup_7.jpg
    - assets/images/hair_makeup/hair_makeup_8.jpg
    - assets/images/hair_makeup/hair_makeup_9.jpg
    - assets/images/hair_makeup/hair_makeup_10.jpg
    - assets/images/hair_makeup/hair_makeup_11.jpg
    - assets/images/hair_makeup/hair_makeup_12.jpg
    - assets/images/hair_makeup/hair_makeup_13.jpg
    - assets/images/hair_makeup/hair_makeup_14.jpg
    - assets/images/hair_makeup/hair_makeup_15.jpg
    - assets/images/showroom_event/showroom_event_1.png
    - assets/images/showroom_event/showroom_event_2.jpg
    - assets/images/showroom_event/showroom_event_3.jpg
    - assets/images/showroom_event/showroom_event_4.jpg
    - assets/images/showroom_event/showroom_event_5.jpg
    - assets/images/showroom_event/showroom_event_6.jpg
    - assets/images/showroom_event/showroom_event_7.jpg
    - assets/images/showroom_event/showroom_event_8.jpg
    - assets/images/showroom_event/showroom_event_9.jpg
    - assets/images/card/eliev_atelier_card.jpg
    - assets/images/card/anna_maria_tabaka_card.jpg
    - assets/images/card/marias_platzl_card.jpg
    - assets/images/card/miracle_wedding_card.jpg
    - assets/images/card/regina_card.jpg
    - assets/images/card/kids_in_munich_card.jpg
    - assets/images/card/tasteria_card.jpg
    - assets/images/card/monokelberlin_card.jpg
    - assets/images/card/judith_lorenz_skusa_schmuck_card.jpg
    - assets/images/card/wir_machen_cupcakes_card.jpg
    - assets/images/card/phillip_schmitt_card.jpg
    - assets/images/card/tanja_kugelmann_papier_romantik_card.jpg
    - assets/images/card/alexey_testov_card.jpg
    - assets/images/card/stefan_krovinovic_card.jpg
    - assets/images/card/elto_card.jpg
    - assets/images/card/sebastian_schwarzbach_card.jpg
    - assets/images/card/joern_gropp_adrian_planitz_card.jpg
    - assets/images/card/fabian_richt_card.jpg
    - assets/images/card/alte_gaertnerei_card.jpg
    - assets/images/card/bachelorette_card.jpg
    - assets/images/card/anna_bachkalova_card.jpg
    - assets/images/card/anja_and_friends_musikensemble_card.jpg
    - assets/images/card/hair_makeup_card.jpg
    - assets/images/card/belflair_card.jpg
    - assets/images/card/jessi_konfetti_im_herzen_card.jpg
    - assets/images/kontakt/kontaktseite.png
    - assets/images/background/kosmetische_akupunktur_back.jpg
    - assets/images/background/personal_training_back.jpg
    - assets/images/background/band_back.jpg
    - assets/images/background/chatbot_back.jpg
    - assets/images/background/catering_back.jpg
    - assets/images/background/florist_back.jpg
    - assets/images/background/unterhaltung_back.jpg
    - assets/images/background/bachelorette_back.jpg
    - assets/images/background/hairstyling_makeup_back.jpg
    - assets/images/background/showroom_event_back.jpg
    - assets/images/background/fotografie_back.jpg
    - assets/images/background/patiserie_back.jpg
    - assets/images/background/papeterie_back.jpg
    - assets/images/background/tanzschule_back.jpg
    - assets/images/background/trauringe_back.jpg
    - assets/images/background/location_back.jpg
    - assets/images/background/braut_und_braeutigam_back.jpg
    - assets/images/background/wedding_design_back.jpg
    - assets/images/home/home_1.png
    - assets/images/home/wedding_home.jpg
    - assets/images/checklist/checklist.jpg
    - assets/images/divider/wedding_rings.png
    - assets/images/gaestelist/gaesteliste.png
    - assets/images/budget/budget.png

    # Videos
    - assets/videos/hair_makeup.mp4
    - assets/videos/bachelorette.mp4
    - assets/videos/akupunktur.mp4
    - assets/videos/about_me.mp4
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages

# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family:
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
